import 'dart:io';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:url_launcher/url_launcher.dart';

class ExportService {
  /// Share transcript text via system share sheet
  static Future<void> shareTranscript(
    String text, {
    required String title,
  }) async {
    await Share.share(
      text,
      subject: 'Transcript — $title',
    );
  }

  /// Share summary text via system share sheet
  static Future<void> shareSummary(
    String text, {
    required String title,
  }) async {
    await Share.share(
      text,
      subject: 'Meeting Minutes — $title',
    );
  }

  /// Share action points via system share sheet
  static Future<void> shareActionPoints(
    List<String> actionPoints, {
    required String title,
  }) async {
    if (actionPoints.isEmpty) {
      await Share.share(
        'No action points extracted.',
        subject: 'Action Points — $title',
      );
      return;
    }
    final text = 'ACTION POINTS — $title\n\n' +
        actionPoints.map((a) => '☐ $a').join('\n');
    await Share.share(text, subject: 'Action Points — $title');
  }

  /// Export full meeting content as TXT file and share
  static Future<void> exportAsTxt(
    String content, {
    required String title,
  }) async {
    try {
      final dir = await getTemporaryDirectory();
      final safeTitle = title.replaceAll(RegExp(r'[^\w\s-]'), '').trim();
      final file = File('${dir.path}/$safeTitle.txt');
      await file.writeAsString(content);
      await Share.shareXFiles(
        [XFile(file.path)],
        subject: title,
      );
    } catch (e) {
      // Fallback to plain text share
      await Share.share(content, subject: title);
    }
  }

  /// Export full meeting content as PDF file and share
  static Future<void> exportAsPdf(
    String content, {
    required String title,
  }) async {
    try {
      final pdf = pw.Document();
      final lines = content.split('\n');

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(32),
          header: (context) => pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                title,
                style: pw.TextStyle(
                  fontSize: 20,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.Text(
                'Generated by Clareon',
                style: const pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.grey,
                ),
              ),
              pw.Divider(),
              pw.SizedBox(height: 8),
            ],
          ),
          build: (context) => [
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: lines.map((line) {
                // Section headers
                if (line.startsWith('───')) {
                  return pw.Padding(
                    padding: const pw.EdgeInsets.only(top: 16, bottom: 8),
                    child: pw.Text(
                      line.replaceAll('─', '').trim(),
                      style: pw.TextStyle(
                        fontSize: 14,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.blue800,
                      ),
                    ),
                  );
                }
                // Empty lines
                if (line.trim().isEmpty) {
                  return pw.SizedBox(height: 6);
                }
                // Regular text
                return pw.Padding(
                  padding: const pw.EdgeInsets.only(bottom: 3),
                  child: pw.Text(
                    line,
                    style: const pw.TextStyle(fontSize: 11),
                  ),
                );
              }).toList(),
            ),
          ],
        ),
      );

      // Save to temp file
      final dir = await getTemporaryDirectory();
      final safeTitle = title.replaceAll(RegExp(r'[^\w\s-]'), '').trim();
      final file = File('${dir.path}/$safeTitle.pdf');
      await file.writeAsBytes(await pdf.save());

      // Share the PDF
      await Share.shareXFiles(
        [XFile(file.path)],
        subject: title,
      );
    } catch (e) {
      // Fallback to text share
      await Share.share(content, subject: title);
    }
  }

  /// Open email app with meeting content pre-filled
  static Future<void> shareViaEmail(
    String content, {
    required String title,
  }) async {
    final subject = Uri.encodeComponent('Meeting Notes — $title');
    final body = Uri.encodeComponent(content);
    final uri = Uri.parse('mailto:?subject=$subject&body=$body');

    if (await canLaunchUrl(uri)) {
      await launchUrl(uri);
    } else {
      // Fallback to share sheet if no email app
      await Share.share(content, subject: 'Meeting Notes — $title');
    }
  }

  /// Share via KingsChat if installed, fallback to share sheet
  static Future<void> shareViaKingsChat(
    String content, {
    required String title,
  }) async {
    // Try KingsChat deep link first
    final kingsChatUri = Uri.parse(
      'kingschat://share?text=${Uri.encodeComponent(content)}',
    );

    if (await canLaunchUrl(kingsChatUri)) {
      await launchUrl(kingsChatUri);
    } else {
      // Fallback to system share — user can pick KingsChat manually
      await Share.share(
        content,
        subject: 'Meeting Notes — $title',
      );
    }
  }
}